### PR TITLE
english translations

### PR DESCRIPTION
**Pull request by fritzmg**

### CODE REVIEW

**Comment by iCodr8** [comment]
Is it possible to make these changes on this project (because of contao 4 support)?
https://github.com/Craffft/css-style-selector-bundle

**Comment by fritzmg** [comment]
Sure, I can re-create the PR there.

**Comment by iCodr8** [comment]
Nice, thanks!

**Comment by fritzmg** [comment]
Done: https://github.com/Craffft/css-style-selector-bundle/pull/1

**Pull request closed without merging**
